/** an Al Naiyr production, all right reserved. Une production Al naiyr, tous droits réservés*/ 
package com.alnaiyr.ressources.angelcodefont;
import org.newdawn.slick.AngelCodeFont;
/** 
 *@autogenerated
 *@author IgoЯ 
 *@version 1.0
 */
public enum LailaAngelCodeFont{
 ARABOLICA,
 SQUARE; 

public AngelCodeFont angelcodefont; 


}
