/** an Al Naiyr production, all right reserved. Une production Al naiyr, tous droits rÃ©servÃ©s*/ 
package com.alnaiyr.ressources.angelcodefont;
import org.newdawn.slick.AngelCodeFont;
/** 
 *@autogenerated
 *@author IgoÐ¯ 
 *@version 1.0
 */
public enum ToroAngelCodeFont{
 ARABOLICA,
 SQUARE; 

public AngelCodeFont angelcodefont; 


}
