/** an Al Naiyr production, all right reserved. Une production Al naiyr, tous droits rÃ©servÃ©s*/ 
package com.alnaiyr.ressources.spritesheet;
import com.alnaiyr.display.renderables.render.rewrite.SpriteSheet;
/** 
 *@autogenerated
 *@author IgoÐ¯ 
 *@version 1.0
 */
public enum ToroSpriteSheet{
 TORO,
 HUMAIN; 

public SpriteSheet spritesheet; 


}
