/** an Al Naiyr production, all right reserved. Une production Al naiyr, tous droits réservés*/ 
package com.alnaiyr.ressources.image;
import com.alnaiyr.display.renderables.render.rewrite.Image;
/** 
 *@autogenerated
 *@author IgoЯ 
 *@version 1.0
 */
public enum ToroImage{
 CHECKBOX1,
 CHECK1,
 GUIARROW,
 GUISHAPE,
 BACKGROUND; 

public Image image; 


}
