/** an Al Naiyr production, all right reserved. Une production Al naiyr, tous droits rÃ©servÃ©s*/ 
package com.alnaiyr.ressources.image;
import com.alnaiyr.display.renderables.render.rewrite.Image;
/** 
 *@autogenerated
 *@author IgoÐ¯ 
 *@version 1.0
 */
public enum ToroImage{
 CHECKBOX1,
 CHECK1,
 GUIARROW,
 GUISHAPE,
 BACKGROUND0,
 BACKGROUND1,
 BACKGROUND2,
 BACKGROUND3,
 BACKGROUND4,
 BACKGROUND5; 

public Image image; 


}
